### ISSUE TITLE
Do you actually need to throw?

### ISSUE THREAD

**Issue by dcherman** [dmethvin/jquery-deferred-reporter#2]
I don't think you actually need to throw the error in order to get at the stacktrace, but rather you could probably just do `return (new Error()).stack`

You could also use `Error.captureStackTrace` in Chrome in order to clean it up a bit, or  you could manually tinker with the stack value in order to remove this function call from the stacktrace since size probably doesn't matter that much for this plugin.

**Comment by dmethvin** [comment]
There seem to be at least a few supported browsers that only provide the stack on thrown errors, for example IE10, so I'd probably just keep it this way for simplicity. 

There isn't a standard form for the stack string so I had just dumped it as-is as a proof of concept. If this is going to continue as a standalone plugin, which seems likely per the discussion in https://github.com/jquery/jquery/pull/2737, I agree it would be better to clean this up a bit so that it has a standard form and the jQuery-internal methods don't show in the stack, confusing people.

**Comment by dmethvin** [comment]
Based on the check I did with IE10 it looked like we did need to throw.
